"use client";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "bootstrap/dist/css/bootstrap.css";
import "./style.css";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <div className="d-flex">
          <div className={"d-flex flex-row"}>
            <div className={""}>
              <Header />
            </div>
            <div className={""}>{children}</div>
          </div>
          <div className="fixed-bottom">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
